import Head from "next/head";
import Image from "next/image";
import Header from "../assets/components/header/index";
import Form from "../assets/components/form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <nav>
          {" "}
          <Header />
        </nav>
        <main>
          <h2 id="sub_heading">Generate as many UUID as you wish for free!</h2>
          <div id="forms">
            <Form
              uuid="4b49c6d4-e566-11eb-ba80-0242ac130004"
              version="version 1"
            />
            <b id="or">
              _____________________<span>Or</span>_____________________
            </b>
            <Form
              uuid="4b49c6d4-e566-11eb-ba80-0242ac130004"
              version="version 4"
            />
          </div>
        </main>
      </body>
    </div>
  );
}
